version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb_container
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "9091:5432"